#!/bin/bash
# A silly script to generate the needed output from an specific folder system
# The order of print should be specified into table_order
# This script is dumb but I like to be organized. In some whay

table_order=(PERSONA CLIENTE DIRECTOR TARJETA REGIMEN TEMPORADA RESERVA HOTEL OCUPACION TIPO HABITACION PRECIO INSTALACION ALQUILABLE USO R_HABITACION_PRECIO R_HABITACION_RESERVA R_RESERVA_CLIENTE R_ALQUILABLE_PRECIO)

if [ -z "$1" ] # No arguments
then
    echo "Command needs one of the following arguments:
    data   - Show insert commands for all tables
    tables - Show table creation commands for all tables
default full   - Show table and insert commands for all tables"
else
    for table in "${table_order[@]}"; do
        case $1 in 
            data)
                cat "./$table/data"
                ;;

            tables)
                cat "./$table/create"
                ;;

            full)   
                cat "./$table/create"
                cat "./$table/data"
                ;;
            *)
                echo "Not a valid argument"
                exit 1
        esac

        echo ""
    done
fi